---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
    when: ansible_distribution == "ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "Ubuntu"
